#This file is required for the okta_saml gem, but we clobber them in the okta initializer

development:
  idp_sso_target_url:
  idp_cert_fingerprint:

test:
  idp_sso_target_url:
  idp_cert_fingerprint:

production:
  idp_sso_target_url:
  idp_cert_fingerprint:

